#!/bin/bash -e

CRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars

echo "## Create namespace blue"
kubectl create ns blue || true

echo "## color-app deployment"
kubectl apply -f blue/color-app.yaml -n blue

echo "## color-app service"
kubectl apply -f blue/color-svc.yaml -n blue

echo "## create firewall rule to enable node port"
gcloud compute firewall-rules create allow-${BLUE_PORT} \
  --allow tcp:${BLUE_PORT} \
  --target-tags worker \
  --network ${NETWORK} \
  --source-ranges 0.0.0.0/0

echo "## check if color-app pods are running"
kubectl get pods -l run=color-app -n blue

echo "## access color-app on below url"
echo "http://${PUB_IP}:${BLUE_PORT}/"
echo "## Please check if you get BLUE color background"
