#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars

echo "## Create namespace green"
kubectl create ns green || true

echo "## color-app deployment"
kubectl apply -f ${SCRIPTPATH}/green/color-app.yaml -n green

echo "## color-app service"
kubectl apply -f ${SCRIPTPATH}/green/color-svc.yaml -n green

echo "## create firewall rule to enable node port"
gcloud compute firewall-rules create allow-${GREEN_PORT} \
  --allow tcp:${GREEN_PORT} \
  --target-tags worker \
  --network ${NETWORK} \
  --source-ranges 0.0.0.0/0

echo "## check if color-app pods are running"
kubectl get pods -l run=color-app -n green

echo "## access color-app on below url"
echo "http://${PUB_IP}:${GREEN_PORT}/"
echo "## Please check if you get GREEN color background"
