#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars

echo "## Updating color app to point to green version"
kubectl set image deployment/color-app color-app=k8sadmin/blue_green:2.0 -n blue

echo "## wait for few secs to start pods"
wait 5

echo "## check if color-app pods are running"
kubectl get pods -l run=color-app -n blue

echo "## access new color-app on below url"
echo "http://${PUB_IP}:${BLUE_PORT}/"
echo "## Please check if you get GREEN color background"
