#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

echo "## hello-world-canary deployment"
kubectl apply -f ${SCRIPTPATH}/manifests/hello-world-canary.yaml

echo "## wait for few seconds to start hello-world-canary pods"
sleep 5

echo "## check if hello-world-canary pods are running"
kubectl get pods -n development -l run=hello-world -l track=canary
