#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars

echo "## hello-world deployment"
kubectl apply -f manifests/hello-world.yaml

echo "## hello-world service"
kubectl apply -f manifests/hello-world-svc.yaml

echo "## create firewall rule to enable node port"
gcloud compute firewall-rules create allow-${CANARY_PORT} \
  --allow tcp:${CANARY_PORT} \
  --target-tags worker \
  --network ${NETWORK} \
  --source-ranges 0.0.0.0/0

echo "## check if hello-world pods are running"
kubectl get pods -n development -l run=hello-world
