apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-world
  name: hello-world
  namespace: development
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5  
  selector:
    matchLabels:
      run: hello-world
  template:
    metadata:
      labels:
        run: hello-world
        track: stable
    spec:
      containers:
      - image: k8sadmin/hello_world:1.0
        imagePullPolicy: Always
        name: hello-world
        ports:
        - name: http
          containerPort: 80
