#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars
echo "## Press ctrl+c to exit"
while true;
do
    sleep 1;
    curl http://${PUB_IP}:${CANARY_PORT}/
done
