#!/bin/bash -e

echo "## Bringup jenkins instance"
gcloud compute instances create jenkins \
	--zone=${ZONE} \
	--machine-type=${MACHINE_TYPE} \
	--can-ip-forward \
	--subnet=default \
	--metadata=Name=Jenkins \
	--maintenance-policy=MIGRATE \
	--scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
	--tags=jenkins-server \
	--image=ubuntu-1804-bionic-v20190617 \
	--image-project=ubuntu-os-cloud \
	--boot-disk-size=50GB \
	--boot-disk-type=pd-standard \
	--boot-disk-device-name=jenkins

echo "## Create firewall rule to allow jenkins port"
gcloud compute firewall-rules create default-allow-8080 \
	--direction=INGRESS \
	--priority=1000 \
	--network=default \
	--action=ALLOW \
	--rules=tcp:8080 \
	--source-ranges=0.0.0.0/0 \
	--target-tags=jenkins-server
