#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars
EXTERNAL_IP=$(gcloud compute instances describe jenkins --zone=${ZONE} --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
JENKINS_URL="http://${EXTERNAL_IP}:8080"

echo "## Downloading jenkins-cli.jar"
wget ${JENKINS_URL}/jnlpJars/jenkins-cli.jar

echo "## Importing jobs into jenkins"
java -jar jenkins-cli.jar -s ${JENKINS_URL} create-job hello-world-helm  < ${SCRIPTPATH}/jobs/hello-world-helm.xml
java -jar jenkins-cli.jar -s ${JENKINS_URL} create-job mynginx  < ${SCRIPTPATH}/jobs/mynginx.xml
