#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/vars

EXTERNAL_IP=$(gcloud compute instances describe jenkins --zone=${ZONE} --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
JENKINS_URL="http://${EXTERNAL_IP}:8080"

echo "## Generating jenkins inventory"
echo "[jenkins]" > ${INV_FILE}
echo ${EXTERNAL_IP} >> ${INV_FILE} 

echo "[all:vars]" >> ${INV_FILE}
echo "ansible_python_interpreter=/usr/bin/python3" >> ${INV_FILE}

echo "## Contents of inventory file"
cat ${INV_FILE}

export ANSIBLE_HOST_KEY_CHECKING=False
echo "## Installing prerequisites for jenkins"
ansible-playbook -i ${INV_FILE} ${SCRIPTPATH}/jenkins-prereq.yaml --private-key=${PRIVATE_KEY}

echo "## Login to jenkins at below url"
echo "${JENKINS_URL}"
