#!/bin/bash

node=$(kubectl get pods -l app=mynginx -n development -o jsonpath='{.items[*].spec.nodeName}')
PUB_IP=$(gcloud compute instances describe ${node} --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
SVC_PORT=$(kubectl get svc mynginxsvc -o=jsonpath='{.spec.ports[*].nodePort}')

echo "## Press ctrl+c to exit"
while true;
do
    sleep 1;
    curl http://${PUB_IP}:${SVC_PORT}/
done
