apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: frontend
    servicePort: 80
  rules:
  - host: staging-guestbook.mstakx.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: frontend
          servicePort: 80
