#!/bin/bash -e

- Setup jenkins instance
gcloud compute --project=k8s-test-cluster-228210 instances create jenkins \
	--zone=asia-southeast1-b \
	--machine-type=n1-standard-1 \
	--can-ip-forward \
	--subnet=default \
	--metadata=Name=Jenkins \
	--maintenance-policy=MIGRATE \
	--scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
	--tags=http-server \
	--image=ubuntu-1804-bionic-v20190617 \
	--image-project=ubuntu-os-cloud \
	--boot-disk-size=50GB \
	--boot-disk-type=pd-standard \
	--boot-disk-device-name=jenkins

gcloud compute --project=k8s-test-cluster-228210 firewall-rules create default-allow-8080 --direction=INGRESS --priority=1000 --network=default --action=ALLOW --rules=tcp:8080 --source-ranges=0.0.0.0/0 --target-tags=http-server
