#!/bin/bash

EXTERNAL_IP=$(gcloud compute instances describe jenkins --zone=asia-southeast1-b  --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
JENKINS_URL="http://${EXTERNAL_IP}:8080"

echo "## Downloading jenkins-cli.jar"
wget ${JENKINS_URL}/jnlpJars/jenkins-cli.jar

java -jar jenkins-cli.jar -s ${JENKINS_URL} create-job hello-world-helm-test  < jenkins-jobs/hello-world-helm.xml
java -jar jenkins-cli.jar -s ${JENKINS_URL} create-job mynginx-test  < jenkins-jobs/mynginx.xml
