#!/bin/bash -e

PROJECT_ID=${PROJECT_ID:?"Please specify Unique project id"}
K8S_CLUSTER_NAME=${K8S_CLUSTER_NAME:-"test-cluster"}
K8S_REGION=${K8S_REGION:-"asia-south1"}
NODES_PER_ZONE=${NODES_PER_ZONE:-"2"}
MACHINE_TYPE=${MACHINE_TYPE:-"n1-standard-1"}
K8S_VER=${K8S_VER:-"1.12.8-gke.10"}
CLUSTER_NAME="gke_${PROJECT_ID}_${K8S_REGION}_${K8S_CLUSTER_NAME}"
