#!/bin/bash -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
source ${SCRIPTPATH}/common

echo -e "\n## Installing helm client on your local instance"
curl -LO https://git.io/get_helm.sh
chmod +x get_helm.sh
sudo ./get_helm.sh
rm ./get_helm.sh

echo -e "\n## Set k8s context"
kubectl create ns ${INGRESS_NAME} || true
kubectl config set-context ${CLUSTER_NAME} --namespace=${INGRESS_NAME}
kubectl config use-context ${CLUSTER_NAME} 

echo -e "\n## Initializing helm"
echo "# Creating Service Account for tiller"
kubectl create serviceaccount --namespace kube-system tiller || true

echo "# Creating cluster-role-binding for tiller"
kubectl create clusterrolebinding tiller-cluster-rule --clusterrole=cluster-admin --serviceaccount=kube-system:tiller || true

echo "# Deploying tiller"
helm init --service-account tiller --wait
