apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager
  labels:
    app: alertmanager
    run: alertmanager
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
