kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/alertmanager"
