apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server
  labels:
    app: prometheus
    run: prometheus
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
