apiVersion: v1
kind: Service
metadata:
  labels:
    run: color-svc
  name: color-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    nodePort: 30012
  selector:
    run: color-app
  type: NodePort
